name: community_charts_flutter
version: 1.0.4
description: Material Design charting library for flutter. Forked from google/charts.
repository: https://github.com/juliansteenbakker/community_charts
publish_to: none

environment:
  sdk: ">=3.13.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  community_charts_common:
#    path: ../community_charts_common/
    git:
      url: https://github.com/deckerst/flutter_community_charts.git
      ref: aves
      path: community_charts_common
  collection:
  leak_tracker:
  material_ui:
  meta:

dev_dependencies:
  mockito:
  build_runner:
  flutter_test:
    sdk: flutter